language: java
jdk:
  - openjdk11

branches:
  only:
    - main

before_install:
  - chomd +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
notifications:
  email:
    recipients:
      - yhy5913@gmail.com
script: "./gradlew clean build"