version: "3"
services:
  mongodb:
    image: mongo:3.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongodb:/data/db
    container_name: "mongodb"
    ports:
      - "27017:27017"